### ISSUE TITLE
bin/tt-render uses relative path

### ISSUE THREAD

**Issue by ppisar** [ingydotnet/template-toolkit-simple-pm#3]
bin/tt-render code:

```
#!/usr/bin/perl

use lib 'lib';
use Template::Toolkit::Simple;

Template::Toolkit::Simple->_run_command(@ARGV);
```

The "use lib 'lib';" injects "./lib" into Perl search path list @INC. Adding paths relative to working directory by default is a security bug. (An attacker creates malicious /tmp/lib/Template/Toolkit/Simple.pm, the victim changes into /tmp and executes tt-render.)

Could you remove the "use lib 'lib';" line from the bin/tt-render?

**Comment by ingydotnet** [comment]
Done.Released.Thanks!
